# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dagger < Formula
  desc "Dagger is a programmable deployment system."
  homepage "https://github.com/dagger/dagger"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://dagger-release-34b7b6b5-0436-46d4-939e-a52b1da53244.s3.us-west-2.amazonaws.com/dagger/releases/0.0.1/dagger_0.0.1_darwin_arm64.tar.gz"
      sha256 "aa0f03061c77ddde402a730981c3aa2626e335ccdc5f2740701c9823dbd65a35"

      def install
        bin.install "dagger"
      end
    end
    if Hardware::CPU.intel?
      url "https://dagger-release-34b7b6b5-0436-46d4-939e-a52b1da53244.s3.us-west-2.amazonaws.com/dagger/releases/0.0.1/dagger_0.0.1_darwin_amd64.tar.gz"
      sha256 "0b25f247ed78800f347264a549551b18a3a4f268164b9cfcfede01718919195b"

      def install
        bin.install "dagger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dagger-release-34b7b6b5-0436-46d4-939e-a52b1da53244.s3.us-west-2.amazonaws.com/dagger/releases/0.0.1/dagger_0.0.1_linux_arm64.tar.gz"
      sha256 "45784b48b09404ba841af8c1de90ffb65c6f856df922a37bf03ba079b3c300de"

      def install
        bin.install "dagger"
      end
    end
    if Hardware::CPU.intel?
      url "https://dagger-release-34b7b6b5-0436-46d4-939e-a52b1da53244.s3.us-west-2.amazonaws.com/dagger/releases/0.0.1/dagger_0.0.1_linux_amd64.tar.gz"
      sha256 "ee25c5fa43df4b2f910e3f809f793655a74c07998d08c25c24c2d51f70d9406f"

      def install
        bin.install "dagger"
      end
    end
  end

  test do
    system "#{bin}/dagger version"
  end
end
